sudo: required

services:
  - docker

language: node_js
node_js:
  - '10.10'

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
    - REPO=registry.kassel.works/website

install:
  - npm ci

before_script:
  - echo "$DOCKER_PASS" |
    docker login -u "$DOCKER_USER" --password-stdin registry.kassel.works

script:
  - npm test && npm run build && docker build -t $REPO:$COMMIT .

after_success:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ];
    then echo $TRAVIS_BRANCH;
    else echo $TRAVIS_PULL_REQUEST_BRANCH;
    fi)
  - if [ "$BRANCH" == "master" ];
    docker tag $REPO:$COMMIT "{$REPO}:master"
    fi
  - docker push $REPO
