sudo: required

services:
  - docker

language: node_js
node_js:
  - '10.3'

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}

install:
  - npm ci

script:
  - npm test
  - npm run build

after_success:
  - export REPO=registry.kassel.works/website
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ];
      then echo $TRAVIS_BRANCH;
      else echo $TRAVIS_PULL_REQUEST_BRANCH;
    fi)
  - export TAG=`if [ "$BRANCH" == "master" ];
      then echo "latest";
      else echo $BRANCH; 
    fi`
  - docker login -u="$DOCKER_USER" -p="$DOCKER_PASS" registry.kassel.works
  - docker build -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
