sudo: required

services:
  - docker

language: node_js
node_js:
  - '7.6'

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}

before_install:
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
  - export ENCODED_EMAIL_ADDRESS=`base64 <<< $EMAIL_ADDRESS`
  - echo "{\"email\":\""$ENCODED_EMAIL_ADDRESS"\"}" > settings.json

install:
  - yarn install --pure-lockfile

script:
  - yarn test
  - yarn run build

after_success:
  - export REPO=registry.kassel.works/fallafel
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ];
      then echo $TRAVIS_BRANCH;
      else echo $TRAVIS_PULL_REQUEST_BRANCH;
    fi)
  - export TAG=`if [ "$BRANCH" == "master" ];
      then echo "latest";
      else echo $BRANCH; 
    fi`
  - docker build -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
